version: "3.0"
services:
    zabbix-proxy:
        image: azcorptechbr/zabbix-proxy-6.4
        container_name: zabbix-proxy
        hostname: zabbix-proxy
        ports:
            - :10051:10051
        environment:
            - ZBX_HOSTNAME=$ZBX_HOSTNAME
            - ZBX_SERVER_HOST=$ZBX_SERVER_HOST
            - ZBX_DEBUGLEVEL=$ZBX_DEBUGLEVEL
            - ZBX_TIMEOUT=$ZBX_TIMEOUT
            - ZBX_PROXYLOCALBUFFER=$ZBX_PROXYLOCALBUFFER
            - ZBX_PROXYOFFLINEBUFFER=$ZBX_PROXYOFFLINEBUFFER
            - ZBX_CONFIGFREQUENCY=$ZBX_CONFIGFREQUENCY
            - ZBX_STARTPOLLERS=$ZBX_STARTPOLLERS
            - ZBX_STARTPOLLERSUNREACHABLE=$ZBX_STARTPOLLERSUNREACHABLE
            - ZBX_STARTTRAPPERS=$ZBX_STARTTRAPPERS
            - ZBX_STARTPINGERS=$ZBX_STARTPINGERS
            - ZBX_CACHESIZE=$ZBX_CACHESIZE
            - ZBX_HISTORYCACHESIZE=$ZBX_HISTORYCACHESIZE
            - ZBX_HISTORYINDEXCACHESIZE=$ZBX_HISTORYINDEXCACHESIZE
            - ZBX_STARTVMWARECOLLECTORS=$ZBX_STARTVMWARECOLLECTORS
            - ZBX_VMWAREFREQUENCY=$ZBX_VMWAREFREQUENCY
            - ZBX_VMWAREPERFFREQUENCY=$ZBX_VMWAREPERFFREQUENCY
            - ZBX_VMWARECACHESIZE=$ZBX_VMWARECACHESIZE
            - ZBX_VMWARETIMEOUT=$ZBX_VMWARETIMEOUT
            - TNS_ADMIN=/usr/lib/oracle/12.1/client64/network/admin
            - ZBX_TLSCONNECT=psk
            - ZBX_TLSPSKIDENTITY=$ZBX_HOSTNAME
            - ZBX_TLSPSKFILE=tls.psk
            - ZBX_SERVER_PORT=$ZBX_SERVER_PORT
            - ZBX_ENABLEREMOTECOMMANDS=1
        volumes:
            - /opt/azcorp/zabbix-proxy/scripts/externalscripts:/usr/lib/zabbix/externalscripts:ro
			- /opt/azcorp/zabbix-proxy/scripts/alertscripts:/usr/lib/zabbix/alertscripts
            - /opt/azcorp/zabbix-proxy/tls.psk:/var/lib/zabbix/enc/tls.psk
            - /etc/localtime:/etc/localtime:ro
            - /etc/hosts:/etc/hosts:ro
        restart: unless-stopped
        networks:
           zbx-network:
              ipv4_address: $IP_CONTAINER

    zabbix-agent:
        image: zabbix/zabbix-agent:latest
        container_name: zabbix-agent
        restart: unless-stopped
        depends_on:
            - zabbix-proxy
        environment:
            - ZBX_HOSTNAME=$ZBX_HOSTNAME
            - ZBX_SERVER_HOST= zabbix-proxy
            - ZBX_SERVER_PORT=10051
            - ZBX_METADATA=Linux Proxy
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run
        privileged: true
        networks:
           zbx-network:
              ipv4_address: $IP_CONTAINER_AGENT
networks:
  zbx-network:
    ipam:
      driver: default
      config:
        - subnet: $IP_SUBNET
